logging:
  level:
    cn.alphahub.eport.signature: debug
    org.apache.http: error
    org.springframework.core: warn
    org.springframework.beans: warn
    org.springframework.context: warn
    org.springframework.web: warn
    org.springframework.web.servlet: info
    org.springframework.cloud.openfeign: debug
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.context.support.PropertySourcesPlaceholderConfigurer: info
    org.springframework.security.core.userdetails: debug
    org.springframework.jdbc.datasource.DataSourceTransactionManager: debug
    jdbc.sqltiming: debug
    com.alibaba.cloud.nacos.client: error
    com.alibaba.nacos: error
  file:
    path: ./logs/
    name: ${logging.file.path}/${spring.application.name}.log
  charset:
    file: UTF-8
  logback:
    rollingpolicy:
      max-file-size: 5MB
      clean-history-on-start: true

spring:
  jackson:
    default-property-inclusion: non_null